server:
  port: 9004
spring:
  application:
    name: member-manager
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    ip-address: true
#eureka对info信息的改善
info:
  app.name: gnawococ-microservice
  company.name: www.gnawococ.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$