server:
  port: 9001
eureka:
  instance:
    hostname: registry-center
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
